animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']

print "The animal at 1 is second and is %s." % animals[1]
print "The third(3rd) animal is at 2 and it is a %s." % animals[2]
print "The first(1st) animal is at 0 and it is a %s." % animals[0]
print "The animal at 3 is fourth and is %s." % animals[3]
print "The fifth(5th) animal is at 4 and it is a %s." % animals[4]
print "The animal at 2 is third and is %s." % animals[2]
print "The sixth(6th) animal is at 5 and it is a %s." % animals[5]
print "The animal at 4 is fifth and is %s." % animals[4]
